---
- hosts: "{{hosts}}"  # Hosts will be passed dynamically from command line
  remote_user: root

  vars_files:
    - host_vars/{{hosts}}/vars.yml      # Common vars
    - host_vars/{{hosts}}/vault.yml     # Sensitive vars

  roles:
    # Initial server setup
    - { role: initial_server_setup_role, tags: ["setup", "initial"] }
    
    # LEMP Stack setup
    - { role: mysql_setup_role, tags: ["lemp", "mysql"] }
    - { role: php_setup_role, tags: ["lemp", "php"] }
    - { role: nginx_setup_role, tags: ["lemp", "nginx"] }

  tasks:

    # UFW configuration
    - name: Configure UFW
      import_tasks: tasks/ufw.yml
      tags: ["setup", "ufw"]
    
    # phpMyAdmin configuration
    - name: Install and configure phpMyAdmin
      import_tasks: tasks/phpmyadmin.yml
      tags: ["services", "phpmyadmin"]
    
    # WordPress setup and configuration
    - name: Install and configure WordPress
      import_tasks: tasks/wordpress.yml
      tags: ["services", "wordpress"]

    # Setup additional services
    # s3cmd_setup_role for backup

    # Exporter roles for monitoring
    # node_exporter_role
    # nginx_exporter_role
    # mysql_exporter_role
    # php_exporter_role
