---
user:
  name: enabler
  sudo_password: "{{vault.user.sudo_password}}"
  public_key: /home/stefan/.ssh/id_rsa.pub # The path on host from which playbooks are run
journalctl_max_disk_usage: 1G
mysql_root_password: "{{vault.mysql_root_password}}"
mysql: 
  user: enabler
  password: "{{vault.mysql_user_password}}"
  db: site
php:
  version: 8.1
pma:
  file_path: "/var/www/phpmyadmin"
  blowfish: "{{vault.pma_blowfish_secret}}"
  basic_http_auth:
    file_path: /etc/nginx/pma
    username: enabler
    password: "{{vault.pma_basic_auth_password}}"
  subdomain: pma.edu
wp:
  site_directory: site
  subdomain: wp.edu
# certbot:
#   directory_path: /var/www/letsencrypt # TODO if used needs to be created